services:
  - type: web
    name: aizen-whatsapp-bot
    env: node
    plan: free
    rootDir: "."
    buildCommand: |
      npm cache clean --force
      rm -rf node_modules package-lock.json
      npm install --legacy-peer-deps --ignore-scripts=false --foreground-scripts --verbose
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHARP_IGNORE_GLOBAL_LIBVIPS
        value: "1"