services:
  - type: web
    name: aizen-whatsapp-bot
    env: node
    plan: free
    rootDir: "."
    buildCommand: |
      npm cache clean --force
      rm -rf node_modules package-lock.json
      npm install --legacy-peer-deps
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production